version: "3"
services:

  ubuntu:
    build: .
    image: my-ubuntu
    container_name: ubuntulocal
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command:
      - tail
      - -f
      - /dev/null
    networks:
      - jypnetwork

networks:
  jypnetwork: